name: meilisearch
description: Meilisearch Dart is the Meilisearch API client for Dart and Flutter developers.
version: 0.12.0
homepage: https://meilisearch.com
repository: https://github.com/meilisearch/meilisearch-dart
issue_tracker: https://github.com/meilisearch/meilisearch-dart/issues

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  dio: ^5.0.0
  crypto: ^3.0.1
  collection: ^1.17.0

dev_dependencies:
  test: ^1.0.0
  dart_jsonwebtoken: ^2.3.2
  lints: ">=1.0.1 <3.0.0"
