name: meilisearch
description: Meilisearch Dart is the Meilisearch API client for Dart and Flutter developers.
version: 0.8.0
homepage: https://meilisearch.com
repository: https://github.com/meilisearch/meilisearch-dart
issue_tracker: https://github.com/meilisearch/meilisearch-dart/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^5.0.0
  crypto: ^3.0.1

dev_dependencies:
  test: ^1.0.0
  dart_jsonwebtoken: ^2.3.2
  lints: ^2.0.1
