name: meilisearch
description: Meilisearch Dart is the Meilisearch API client for Dart and Flutter developers.
version: 0.17.0
homepage: https://meilisearch.com
repository: https://github.com/meilisearch/meilisearch-dart
issue_tracker: https://github.com/meilisearch/meilisearch-dart/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.0.0
  crypto: ^3.0.1
  collection: ^1.17.0
  json_annotation: ^4.8.1
  meta: ^1.9.1

dev_dependencies:
  test: ^1.0.0
  dart_jsonwebtoken: ^2.12.2
  lints: ">=2.1.0 <4.0.0"
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  pub_semver: ^2.1.5

screenshots:
  - description: The Meilisearch logo.
    path: screenshots/logo.png
